version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    # user: 1000:1000
    env_file:
      - vaultwarden.env
    volumes:
      - ./vw-data:/data
      - ./logrotate/bitwarden:/etc/logrotate.d/bitwarden:ro

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
      - ./logrotate/caddy:/etc/logrotate.d/caddy:ro
    env_file:
      - caddy.env

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./fail2ban-data:/data
      - ./vw-data:/vw-data
      - ./jails/vaultwarden.local:/etc/fail2ban/jail.d/vaultwarden.local
      - ./jails/vaultwarden-admin.local:/etc/fail2ban/jail.d/vaultwarden-admin.local
      - ./filters/vaultwarden.local:/etc/fail2ban/filter.d/vaultwarden.local
      - ./filters/vaultwarden-admin.local:/etc/fail2ban/filter.d/vaultwarden-admin.local
    env_file:
      - "./fail2ban.env"
    restart: always
